### ISSUE TITLE
X, Y axis selectors  don't update when the dimensions of the data in the scatterplot change

### ISSUE THREAD

**Issue by bleliev** [ManiVaultStudio/Scatterplot#101]
Steps to reproduce: 
Load dataset -> create PCA -> drag PCA in scatterplot -> set PCA components to >3 (for instance 30) -> compute PCA. 

The dataset in the scatterplot is now changed, but the x,y axis selectors still have 2 dimensions. 

Dragging in a different dataset, and then redragging the PCA to the scatterplot gives the correct number of dimensions...

**Comment by alxvth** [comment]
Fixed in #107
