### ISSUE TITLE
Scatterplot crashes when switching to a position pointdataset with less dimensions than the old one.

### ISSUE THREAD

**Issue by jeggermont** [ManiVaultStudio/Scatterplot#98]
When switching from a dataset with more than 2 dimensions and at least one of the visible dimensions is > 1 ManiVault crashes because PointData::extractFullDataForDimensions is called with the wrong dimensionIndex1 or dimensionsIndex2 causing either an assert failure in Debug mode or a crash in Release mode.

The problem is probably that the pointdata for which extractFullDataForDimensions is called is already changed to the new dataset but the dimensionIndex1 and dimensionIndex2 values are still those of the old dataset.

To reproduce:

1. Load a dataset with more than 2 dimensions
2. Open a Scatterplot View on the dataset and select dimensions other than the first 2
3. Perform a tsne analysis on the dataset
4. Drop the tsne embedding pointdataset on the scatterplot positions

**Comment by alxvth** [comment]
Fixed in #110
